export type ProjectGalleryImage = {
  slug: string;
  image: string;
  title: string;
  alt: string;
  city: string;
  category: string;
  categoryLabel: string;
  serviceSlug: string;
  serviceHref: string;
  width: number;
  height: number;
  sizeKb: number;
};

export const projectGallery: ProjectGalleryImage[] = [
  {
    "slug": "ramos-wet-bar-built-ins-tempe-east-valley-az-001",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-tempe-east-valley-az-001.webp",
    "title": "Custom Wet Bar Cabinetry",
    "alt": "Custom wet bar cabinetry and built in storage by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1600,
    "height": 897,
    "sizeKb": 48
  },
  {
    "slug": "ramos-wet-bar-built-ins-gilbert-east-valley-az-002",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-gilbert-east-valley-az-002.webp",
    "title": "Custom Wet Bar Cabinetry",
    "alt": "Custom wet bar cabinetry and built in storage by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1440,
    "height": 1440,
    "sizeKb": 123
  },
  {
    "slug": "ramos-finish-carpentry-mesa-east-valley-az-003",
    "image": "/images/projects/seo/ramos-finish-carpentry-mesa-east-valley-az-003.webp",
    "title": "Wood Ceiling Finish Carpentry",
    "alt": "Wood ceiling finish carpentry detail by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "finish-carpentry",
    "categoryLabel": "Finish Carpentry",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1280,
    "height": 1600,
    "sizeKb": 413
  },
  {
    "slug": "ramos-kitchen-remodeling-chandler-east-valley-az-004",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-chandler-east-valley-az-004.webp",
    "title": "Kitchen Cabinet Remodel",
    "alt": "Kitchen cabinet remodel with custom storage by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 720,
    "height": 960,
    "sizeKb": 59
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-005",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-005.webp",
    "title": "Kitchen Cabinet Remodel",
    "alt": "Kitchen cabinet remodel with custom storage by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1600,
    "height": 1200,
    "sizeKb": 117
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-006",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-006.webp",
    "title": "Kitchen Cabinet Remodel",
    "alt": "Kitchen cabinet remodel with custom storage by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 71
  },
  {
    "slug": "ramos-custom-cabinets-tempe-east-valley-az-007",
    "image": "/images/projects/seo/ramos-custom-cabinets-tempe-east-valley-az-007.webp",
    "title": "Custom Cabinetry Detail",
    "alt": "Custom cabinet detail by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 62
  },
  {
    "slug": "ramos-custom-cabinets-gilbert-east-valley-az-008",
    "image": "/images/projects/seo/ramos-custom-cabinets-gilbert-east-valley-az-008.webp",
    "title": "Custom Cabinetry Detail",
    "alt": "Custom cabinet detail by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 327
  },
  {
    "slug": "ramos-built-ins-mesa-east-valley-az-009",
    "image": "/images/projects/seo/ramos-built-ins-mesa-east-valley-az-009.webp",
    "title": "Living Room Built In Cabinetry",
    "alt": "Living room built in cabinetry and storage by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "built-ins",
    "categoryLabel": "Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 112
  },
  {
    "slug": "ramos-built-ins-chandler-east-valley-az-010",
    "image": "/images/projects/seo/ramos-built-ins-chandler-east-valley-az-010.webp",
    "title": "Living Room Built In Cabinetry",
    "alt": "Living room built in cabinetry and storage by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "built-ins",
    "categoryLabel": "Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 85
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-011",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-011.webp",
    "title": "Custom Kitchen Remodeling Project",
    "alt": "Custom kitchen remodeling project by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 151
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-012",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-012.webp",
    "title": "Custom Kitchen Remodeling Project",
    "alt": "Custom kitchen remodeling project by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 84
  },
  {
    "slug": "ramos-kitchen-remodeling-tempe-east-valley-az-013",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-tempe-east-valley-az-013.webp",
    "title": "Custom Kitchen Remodeling Project",
    "alt": "Custom kitchen remodeling project by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 127
  },
  {
    "slug": "ramos-kitchen-remodeling-gilbert-east-valley-az-014",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-gilbert-east-valley-az-014.webp",
    "title": "Custom Kitchen Remodeling Project",
    "alt": "Custom kitchen remodeling project by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 73
  },
  {
    "slug": "ramos-kitchen-remodeling-mesa-east-valley-az-015",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-mesa-east-valley-az-015.webp",
    "title": "Custom Kitchen Remodeling Project",
    "alt": "Custom kitchen remodeling project by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 108
  },
  {
    "slug": "ramos-kitchen-remodeling-chandler-east-valley-az-016",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-chandler-east-valley-az-016.webp",
    "title": "Custom Kitchen Remodeling Project",
    "alt": "Custom kitchen remodeling project by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1600,
    "height": 1200,
    "sizeKb": 98
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-017",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-017.webp",
    "title": "Custom Kitchen Remodeling Project",
    "alt": "Custom kitchen remodeling project by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 155
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-018",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-018.webp",
    "title": "Custom Kitchen Remodeling Project",
    "alt": "Custom kitchen remodeling project by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 107
  },
  {
    "slug": "ramos-kitchen-remodeling-tempe-east-valley-az-019",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-tempe-east-valley-az-019.webp",
    "title": "Custom Kitchen Remodeling Project",
    "alt": "Custom kitchen remodeling project by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 158
  },
  {
    "slug": "ramos-kitchen-remodeling-gilbert-east-valley-az-020",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-gilbert-east-valley-az-020.webp",
    "title": "Custom Kitchen Remodeling Project",
    "alt": "Custom kitchen remodeling project by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 100
  },
  {
    "slug": "ramos-custom-cabinets-mesa-east-valley-az-021",
    "image": "/images/projects/seo/ramos-custom-cabinets-mesa-east-valley-az-021.webp",
    "title": "Tall Storage Cabinetry",
    "alt": "Tall storage cabinetry with custom cabinet doors by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 51
  },
  {
    "slug": "ramos-custom-cabinets-chandler-east-valley-az-022",
    "image": "/images/projects/seo/ramos-custom-cabinets-chandler-east-valley-az-022.webp",
    "title": "Tall Storage Cabinetry",
    "alt": "Tall storage cabinetry with custom cabinet doors by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 91
  },
  {
    "slug": "ramos-custom-cabinets-scottsdale-east-valley-az-023",
    "image": "/images/projects/seo/ramos-custom-cabinets-scottsdale-east-valley-az-023.webp",
    "title": "Tall Storage Cabinetry",
    "alt": "Tall storage cabinetry with custom cabinet doors by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 106
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-024",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-024.webp",
    "title": "Kitchen Cabinet Installation",
    "alt": "Kitchen cabinet installation and island work by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 171
  },
  {
    "slug": "ramos-kitchen-remodeling-tempe-east-valley-az-025",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-tempe-east-valley-az-025.webp",
    "title": "Kitchen Cabinet Installation",
    "alt": "Kitchen cabinet installation and island work by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 103
  },
  {
    "slug": "ramos-custom-cabinets-gilbert-east-valley-az-026",
    "image": "/images/projects/seo/ramos-custom-cabinets-gilbert-east-valley-az-026.webp",
    "title": "White Cabinet Storage Wall",
    "alt": "White custom cabinet storage wall by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 87
  },
  {
    "slug": "ramos-custom-cabinets-mesa-east-valley-az-027",
    "image": "/images/projects/seo/ramos-custom-cabinets-mesa-east-valley-az-027.webp",
    "title": "White Cabinet Storage Wall",
    "alt": "White custom cabinet storage wall by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 122
  },
  {
    "slug": "ramos-kitchen-remodeling-chandler-east-valley-az-028",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-chandler-east-valley-az-028.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 118
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-029",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-029.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 137
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-030",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-030.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 116
  },
  {
    "slug": "ramos-kitchen-remodeling-tempe-east-valley-az-031",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-tempe-east-valley-az-031.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 216
  },
  {
    "slug": "ramos-kitchen-remodeling-gilbert-east-valley-az-032",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-gilbert-east-valley-az-032.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 165
  },
  {
    "slug": "ramos-kitchen-remodeling-mesa-east-valley-az-033",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-mesa-east-valley-az-033.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 84
  },
  {
    "slug": "ramos-kitchen-remodeling-chandler-east-valley-az-034",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-chandler-east-valley-az-034.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 131
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-035",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-035.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 144
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-036",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-036.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 80
  },
  {
    "slug": "ramos-kitchen-remodeling-tempe-east-valley-az-037",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-tempe-east-valley-az-037.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 89
  },
  {
    "slug": "ramos-kitchen-remodeling-gilbert-east-valley-az-038",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-gilbert-east-valley-az-038.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 98
  },
  {
    "slug": "ramos-kitchen-remodeling-mesa-east-valley-az-039",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-mesa-east-valley-az-039.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 118
  },
  {
    "slug": "ramos-kitchen-remodeling-chandler-east-valley-az-040",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-chandler-east-valley-az-040.webp",
    "title": "Custom Kitchen Cabinet Build",
    "alt": "Custom kitchen cabinet build and remodel by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1198,
    "height": 1600,
    "sizeKb": 103
  },
  {
    "slug": "ramos-custom-cabinets-scottsdale-east-valley-az-041",
    "image": "/images/projects/seo/ramos-custom-cabinets-scottsdale-east-valley-az-041.webp",
    "title": "Bedroom Storage Cabinetry",
    "alt": "Bedroom storage cabinetry by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 114
  },
  {
    "slug": "ramos-commercial-finish-carpentry-phoenix-east-valley-az-042",
    "image": "/images/projects/seo/ramos-commercial-finish-carpentry-phoenix-east-valley-az-042.webp",
    "title": "Commercial Wood Feature Wall",
    "alt": "Commercial wood feature wall and finish carpentry by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "commercial-finish-carpentry",
    "categoryLabel": "Commercial Finish Carpentry",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 199
  },
  {
    "slug": "ramos-built-ins-tempe-east-valley-az-043",
    "image": "/images/projects/seo/ramos-built-ins-tempe-east-valley-az-043.webp",
    "title": "Built In Appliance Cabinetry",
    "alt": "Built in appliance cabinetry and custom shelving by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "built-ins",
    "categoryLabel": "Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 182
  },
  {
    "slug": "ramos-built-ins-gilbert-east-valley-az-044",
    "image": "/images/projects/seo/ramos-built-ins-gilbert-east-valley-az-044.webp",
    "title": "Built In Appliance Cabinetry",
    "alt": "Built in appliance cabinetry and custom shelving by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "built-ins",
    "categoryLabel": "Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1600,
    "height": 1200,
    "sizeKb": 74
  },
  {
    "slug": "ramos-home-remodeling-mesa-east-valley-az-045",
    "image": "/images/projects/seo/ramos-home-remodeling-mesa-east-valley-az-045.webp",
    "title": "Residential Remodeling Prep",
    "alt": "Residential remodeling prep and cabinetry planning by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "home-remodeling",
    "categoryLabel": "Home Remodeling",
    "serviceSlug": "home-remodeling",
    "serviceHref": "/services/home-remodeling",
    "width": 1600,
    "height": 1200,
    "sizeKb": 86
  },
  {
    "slug": "ramos-home-remodeling-chandler-east-valley-az-046",
    "image": "/images/projects/seo/ramos-home-remodeling-chandler-east-valley-az-046.webp",
    "title": "Residential Remodeling Prep",
    "alt": "Residential remodeling prep and cabinetry planning by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "home-remodeling",
    "categoryLabel": "Home Remodeling",
    "serviceSlug": "home-remodeling",
    "serviceHref": "/services/home-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 103
  },
  {
    "slug": "ramos-home-remodeling-scottsdale-east-valley-az-047",
    "image": "/images/projects/seo/ramos-home-remodeling-scottsdale-east-valley-az-047.webp",
    "title": "Residential Remodeling Prep",
    "alt": "Residential remodeling prep and cabinetry planning by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "home-remodeling",
    "categoryLabel": "Home Remodeling",
    "serviceSlug": "home-remodeling",
    "serviceHref": "/services/home-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 64
  },
  {
    "slug": "ramos-built-ins-phoenix-east-valley-az-048",
    "image": "/images/projects/seo/ramos-built-ins-phoenix-east-valley-az-048.webp",
    "title": "Custom Built In Cabinetry",
    "alt": "Custom built in cabinetry and storage by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "built-ins",
    "categoryLabel": "Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 124
  },
  {
    "slug": "ramos-built-ins-tempe-east-valley-az-049",
    "image": "/images/projects/seo/ramos-built-ins-tempe-east-valley-az-049.webp",
    "title": "Custom Built In Cabinetry",
    "alt": "Custom built in cabinetry and storage by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "built-ins",
    "categoryLabel": "Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 284
  },
  {
    "slug": "ramos-built-ins-gilbert-east-valley-az-050",
    "image": "/images/projects/seo/ramos-built-ins-gilbert-east-valley-az-050.webp",
    "title": "Custom Built In Cabinetry",
    "alt": "Custom built in cabinetry and storage by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "built-ins",
    "categoryLabel": "Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 60
  },
  {
    "slug": "ramos-built-ins-mesa-east-valley-az-051",
    "image": "/images/projects/seo/ramos-built-ins-mesa-east-valley-az-051.webp",
    "title": "Custom Built In Cabinetry",
    "alt": "Custom built in cabinetry and storage by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "built-ins",
    "categoryLabel": "Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 124
  },
  {
    "slug": "ramos-built-ins-chandler-east-valley-az-052",
    "image": "/images/projects/seo/ramos-built-ins-chandler-east-valley-az-052.webp",
    "title": "Custom Built In Cabinetry",
    "alt": "Custom built in cabinetry and storage by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "built-ins",
    "categoryLabel": "Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 152
  },
  {
    "slug": "ramos-laundry-room-cabinets-scottsdale-east-valley-az-053",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-scottsdale-east-valley-az-053.webp",
    "title": "Laundry Room Cabinetry",
    "alt": "Laundry room cabinetry and storage by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 116
  },
  {
    "slug": "ramos-laundry-room-cabinets-phoenix-east-valley-az-054",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-phoenix-east-valley-az-054.webp",
    "title": "Laundry Room Cabinetry",
    "alt": "Laundry room cabinetry and storage by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 117
  },
  {
    "slug": "ramos-cabinet-installation-tempe-east-valley-az-055",
    "image": "/images/projects/seo/ramos-cabinet-installation-tempe-east-valley-az-055.webp",
    "title": "Cabinet Installation Progress",
    "alt": "Cabinet installation progress for a remodeling project by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 87
  },
  {
    "slug": "ramos-cabinet-installation-gilbert-east-valley-az-056",
    "image": "/images/projects/seo/ramos-cabinet-installation-gilbert-east-valley-az-056.webp",
    "title": "Cabinet Installation Progress",
    "alt": "Cabinet installation progress for a remodeling project by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 92
  },
  {
    "slug": "ramos-cabinet-installation-mesa-east-valley-az-057",
    "image": "/images/projects/seo/ramos-cabinet-installation-mesa-east-valley-az-057.webp",
    "title": "Cabinet Installation Progress",
    "alt": "Cabinet installation progress for a remodeling project by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 86
  },
  {
    "slug": "ramos-cabinet-installation-chandler-east-valley-az-058",
    "image": "/images/projects/seo/ramos-cabinet-installation-chandler-east-valley-az-058.webp",
    "title": "Cabinet Installation Progress",
    "alt": "Cabinet installation progress for a remodeling project by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 102
  },
  {
    "slug": "ramos-cabinet-installation-scottsdale-east-valley-az-059",
    "image": "/images/projects/seo/ramos-cabinet-installation-scottsdale-east-valley-az-059.webp",
    "title": "Cabinet Installation Progress",
    "alt": "Cabinet installation progress for a remodeling project by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 119
  },
  {
    "slug": "ramos-cabinet-installation-phoenix-east-valley-az-060",
    "image": "/images/projects/seo/ramos-cabinet-installation-phoenix-east-valley-az-060.webp",
    "title": "Cabinet Installation Progress",
    "alt": "Cabinet installation progress for a remodeling project by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1600,
    "height": 1200,
    "sizeKb": 68
  },
  {
    "slug": "ramos-home-remodeling-tempe-east-valley-az-061",
    "image": "/images/projects/seo/ramos-home-remodeling-tempe-east-valley-az-061.webp",
    "title": "Interior Remodeling Progress",
    "alt": "Interior remodeling progress and carpentry prep by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "home-remodeling",
    "categoryLabel": "Home Remodeling",
    "serviceSlug": "home-remodeling",
    "serviceHref": "/services/home-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 113
  },
  {
    "slug": "ramos-home-remodeling-gilbert-east-valley-az-062",
    "image": "/images/projects/seo/ramos-home-remodeling-gilbert-east-valley-az-062.webp",
    "title": "Interior Remodeling Progress",
    "alt": "Interior remodeling progress and carpentry prep by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "home-remodeling",
    "categoryLabel": "Home Remodeling",
    "serviceSlug": "home-remodeling",
    "serviceHref": "/services/home-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 85
  },
  {
    "slug": "ramos-home-remodeling-mesa-east-valley-az-063",
    "image": "/images/projects/seo/ramos-home-remodeling-mesa-east-valley-az-063.webp",
    "title": "Interior Remodeling Progress",
    "alt": "Interior remodeling progress and carpentry prep by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "home-remodeling",
    "categoryLabel": "Home Remodeling",
    "serviceSlug": "home-remodeling",
    "serviceHref": "/services/home-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 78
  },
  {
    "slug": "ramos-home-remodeling-chandler-east-valley-az-064",
    "image": "/images/projects/seo/ramos-home-remodeling-chandler-east-valley-az-064.webp",
    "title": "Interior Remodeling Progress",
    "alt": "Interior remodeling progress and carpentry prep by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "home-remodeling",
    "categoryLabel": "Home Remodeling",
    "serviceSlug": "home-remodeling",
    "serviceHref": "/services/home-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 103
  },
  {
    "slug": "ramos-home-remodeling-scottsdale-east-valley-az-065",
    "image": "/images/projects/seo/ramos-home-remodeling-scottsdale-east-valley-az-065.webp",
    "title": "Interior Remodeling Progress",
    "alt": "Interior remodeling progress and carpentry prep by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "home-remodeling",
    "categoryLabel": "Home Remodeling",
    "serviceSlug": "home-remodeling",
    "serviceHref": "/services/home-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 104
  },
  {
    "slug": "ramos-home-remodeling-phoenix-east-valley-az-066",
    "image": "/images/projects/seo/ramos-home-remodeling-phoenix-east-valley-az-066.webp",
    "title": "Interior Remodeling Progress",
    "alt": "Interior remodeling progress and carpentry prep by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "home-remodeling",
    "categoryLabel": "Home Remodeling",
    "serviceSlug": "home-remodeling",
    "serviceHref": "/services/home-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 113
  },
  {
    "slug": "ramos-wood-countertops-tempe-east-valley-az-067",
    "image": "/images/projects/seo/ramos-wood-countertops-tempe-east-valley-az-067.webp",
    "title": "Custom Wood Countertop Detail",
    "alt": "Custom wood countertop detail by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "wood-countertops",
    "categoryLabel": "Wood Countertops",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 720,
    "height": 1280,
    "sizeKb": 181
  },
  {
    "slug": "ramos-wood-countertops-gilbert-east-valley-az-068",
    "image": "/images/projects/seo/ramos-wood-countertops-gilbert-east-valley-az-068.webp",
    "title": "Custom Wood Countertop Detail",
    "alt": "Custom wood countertop detail by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "wood-countertops",
    "categoryLabel": "Wood Countertops",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1600,
    "height": 1200,
    "sizeKb": 302
  },
  {
    "slug": "ramos-mudroom-built-ins-mesa-east-valley-az-069",
    "image": "/images/projects/seo/ramos-mudroom-built-ins-mesa-east-valley-az-069.webp",
    "title": "Mudroom Built In Storage",
    "alt": "Mudroom built in storage cabinetry by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "mudroom-built-ins",
    "categoryLabel": "Mudroom Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 55
  },
  {
    "slug": "ramos-mudroom-built-ins-chandler-east-valley-az-070",
    "image": "/images/projects/seo/ramos-mudroom-built-ins-chandler-east-valley-az-070.webp",
    "title": "Mudroom Built In Storage",
    "alt": "Mudroom built in storage cabinetry by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "mudroom-built-ins",
    "categoryLabel": "Mudroom Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 139
  },
  {
    "slug": "ramos-cabinet-installation-scottsdale-east-valley-az-071",
    "image": "/images/projects/seo/ramos-cabinet-installation-scottsdale-east-valley-az-071.webp",
    "title": "Kitchen Cabinet Installation",
    "alt": "Kitchen cabinet installation in progress by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 100
  },
  {
    "slug": "ramos-cabinet-installation-phoenix-east-valley-az-072",
    "image": "/images/projects/seo/ramos-cabinet-installation-phoenix-east-valley-az-072.webp",
    "title": "Kitchen Cabinet Installation",
    "alt": "Kitchen cabinet installation in progress by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 44
  },
  {
    "slug": "ramos-cabinet-installation-tempe-east-valley-az-073",
    "image": "/images/projects/seo/ramos-cabinet-installation-tempe-east-valley-az-073.webp",
    "title": "Kitchen Cabinet Installation",
    "alt": "Kitchen cabinet installation in progress by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 68
  },
  {
    "slug": "ramos-cabinet-installation-gilbert-east-valley-az-074",
    "image": "/images/projects/seo/ramos-cabinet-installation-gilbert-east-valley-az-074.webp",
    "title": "Kitchen Cabinet Installation",
    "alt": "Kitchen cabinet installation in progress by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 153
  },
  {
    "slug": "ramos-cabinet-installation-mesa-east-valley-az-075",
    "image": "/images/projects/seo/ramos-cabinet-installation-mesa-east-valley-az-075.webp",
    "title": "Kitchen Cabinet Installation",
    "alt": "Kitchen cabinet installation in progress by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 105
  },
  {
    "slug": "ramos-kitchen-remodeling-chandler-east-valley-az-076",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-chandler-east-valley-az-076.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 143
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-077",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-077.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 177
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-078",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-078.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 80
  },
  {
    "slug": "ramos-kitchen-remodeling-tempe-east-valley-az-079",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-tempe-east-valley-az-079.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 124
  },
  {
    "slug": "ramos-kitchen-remodeling-gilbert-east-valley-az-080",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-gilbert-east-valley-az-080.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 218
  },
  {
    "slug": "ramos-kitchen-remodeling-mesa-east-valley-az-081",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-mesa-east-valley-az-081.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 143
  },
  {
    "slug": "ramos-kitchen-remodeling-chandler-east-valley-az-082",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-chandler-east-valley-az-082.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 110
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-083",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-083.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 384
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-084",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-084.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 84
  },
  {
    "slug": "ramos-kitchen-remodeling-tempe-east-valley-az-085",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-tempe-east-valley-az-085.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 126
  },
  {
    "slug": "ramos-kitchen-remodeling-gilbert-east-valley-az-086",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-gilbert-east-valley-az-086.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 256
  },
  {
    "slug": "ramos-kitchen-remodeling-mesa-east-valley-az-087",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-mesa-east-valley-az-087.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1600,
    "height": 1200,
    "sizeKb": 119
  },
  {
    "slug": "ramos-kitchen-remodeling-chandler-east-valley-az-088",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-chandler-east-valley-az-088.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 104
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-089",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-089.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1600,
    "height": 1200,
    "sizeKb": 131
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-090",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-090.webp",
    "title": "Custom Kitchen Remodel",
    "alt": "Custom kitchen remodel with cabinet installation by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 80
  },
  {
    "slug": "ramos-materials-process-tempe-east-valley-az-091",
    "image": "/images/projects/seo/ramos-materials-process-tempe-east-valley-az-091.webp",
    "title": "Custom Cabinet Shop Detail",
    "alt": "Custom cabinet shop detail and finish material by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "materials-process",
    "categoryLabel": "Materials Process",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 186
  },
  {
    "slug": "ramos-materials-process-gilbert-east-valley-az-092",
    "image": "/images/projects/seo/ramos-materials-process-gilbert-east-valley-az-092.webp",
    "title": "Custom Cabinet Shop Detail",
    "alt": "Custom cabinet shop detail and finish material by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "materials-process",
    "categoryLabel": "Materials Process",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 125
  },
  {
    "slug": "ramos-materials-process-mesa-east-valley-az-093",
    "image": "/images/projects/seo/ramos-materials-process-mesa-east-valley-az-093.webp",
    "title": "Custom Cabinet Shop Detail",
    "alt": "Custom cabinet shop detail and finish material by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "materials-process",
    "categoryLabel": "Materials Process",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 186
  },
  {
    "slug": "ramos-materials-process-chandler-east-valley-az-094",
    "image": "/images/projects/seo/ramos-materials-process-chandler-east-valley-az-094.webp",
    "title": "Custom Cabinet Shop Detail",
    "alt": "Custom cabinet shop detail and finish material by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "materials-process",
    "categoryLabel": "Materials Process",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 97
  },
  {
    "slug": "ramos-materials-process-scottsdale-east-valley-az-095",
    "image": "/images/projects/seo/ramos-materials-process-scottsdale-east-valley-az-095.webp",
    "title": "Custom Cabinet Shop Detail",
    "alt": "Custom cabinet shop detail and finish material by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "materials-process",
    "categoryLabel": "Materials Process",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1080,
    "height": 1351,
    "sizeKb": 85
  },
  {
    "slug": "ramos-materials-process-phoenix-east-valley-az-096",
    "image": "/images/projects/seo/ramos-materials-process-phoenix-east-valley-az-096.webp",
    "title": "Custom Cabinet Shop Detail",
    "alt": "Custom cabinet shop detail and finish material by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "materials-process",
    "categoryLabel": "Materials Process",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 60
  },
  {
    "slug": "ramos-materials-process-tempe-east-valley-az-097",
    "image": "/images/projects/seo/ramos-materials-process-tempe-east-valley-az-097.webp",
    "title": "Custom Cabinet Shop Detail",
    "alt": "Custom cabinet shop detail and finish material by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "materials-process",
    "categoryLabel": "Materials Process",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 62
  },
  {
    "slug": "ramos-bathroom-remodeling-gilbert-east-valley-az-098",
    "image": "/images/projects/seo/ramos-bathroom-remodeling-gilbert-east-valley-az-098.webp",
    "title": "Custom Bathroom Vanity",
    "alt": "Custom bathroom vanity and cabinet installation by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "bathroom-remodeling",
    "categoryLabel": "Bathroom Remodeling",
    "serviceSlug": "bathroom-remodeling",
    "serviceHref": "/services/bathroom-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 104
  },
  {
    "slug": "ramos-bathroom-remodeling-mesa-east-valley-az-099",
    "image": "/images/projects/seo/ramos-bathroom-remodeling-mesa-east-valley-az-099.webp",
    "title": "Custom Bathroom Vanity",
    "alt": "Custom bathroom vanity and cabinet installation by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "bathroom-remodeling",
    "categoryLabel": "Bathroom Remodeling",
    "serviceSlug": "bathroom-remodeling",
    "serviceHref": "/services/bathroom-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 96
  },
  {
    "slug": "ramos-bathroom-remodeling-chandler-east-valley-az-100",
    "image": "/images/projects/seo/ramos-bathroom-remodeling-chandler-east-valley-az-100.webp",
    "title": "Custom Bathroom Vanity",
    "alt": "Custom bathroom vanity and cabinet installation by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "bathroom-remodeling",
    "categoryLabel": "Bathroom Remodeling",
    "serviceSlug": "bathroom-remodeling",
    "serviceHref": "/services/bathroom-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 124
  },
  {
    "slug": "ramos-commercial-finish-carpentry-scottsdale-east-valley-az-101",
    "image": "/images/projects/seo/ramos-commercial-finish-carpentry-scottsdale-east-valley-az-101.webp",
    "title": "Commercial Wood Wall Feature",
    "alt": "Commercial wood wall feature and finish carpentry by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "commercial-finish-carpentry",
    "categoryLabel": "Commercial Finish Carpentry",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1600,
    "height": 1200,
    "sizeKb": 192
  },
  {
    "slug": "ramos-mudroom-built-ins-phoenix-east-valley-az-102",
    "image": "/images/projects/seo/ramos-mudroom-built-ins-phoenix-east-valley-az-102.webp",
    "title": "Mudroom Bench and Storage",
    "alt": "Mudroom bench and storage cabinetry by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "mudroom-built-ins",
    "categoryLabel": "Mudroom Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 57
  },
  {
    "slug": "ramos-mudroom-built-ins-tempe-east-valley-az-103",
    "image": "/images/projects/seo/ramos-mudroom-built-ins-tempe-east-valley-az-103.webp",
    "title": "Mudroom Bench and Storage",
    "alt": "Mudroom bench and storage cabinetry by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "mudroom-built-ins",
    "categoryLabel": "Mudroom Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 29
  },
  {
    "slug": "ramos-mudroom-built-ins-gilbert-east-valley-az-104",
    "image": "/images/projects/seo/ramos-mudroom-built-ins-gilbert-east-valley-az-104.webp",
    "title": "Mudroom Bench and Storage",
    "alt": "Mudroom bench and storage cabinetry by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "mudroom-built-ins",
    "categoryLabel": "Mudroom Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 49
  },
  {
    "slug": "ramos-mudroom-built-ins-mesa-east-valley-az-105",
    "image": "/images/projects/seo/ramos-mudroom-built-ins-mesa-east-valley-az-105.webp",
    "title": "Mudroom Bench and Storage",
    "alt": "Mudroom bench and storage cabinetry by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "mudroom-built-ins",
    "categoryLabel": "Mudroom Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 31
  },
  {
    "slug": "ramos-mudroom-built-ins-chandler-east-valley-az-106",
    "image": "/images/projects/seo/ramos-mudroom-built-ins-chandler-east-valley-az-106.webp",
    "title": "Mudroom Bench and Storage",
    "alt": "Mudroom bench and storage cabinetry by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "mudroom-built-ins",
    "categoryLabel": "Mudroom Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 133
  },
  {
    "slug": "ramos-wet-bar-built-ins-scottsdale-east-valley-az-107",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-scottsdale-east-valley-az-107.webp",
    "title": "Custom Wet Bar Built In",
    "alt": "Custom wet bar built in cabinetry by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 129
  },
  {
    "slug": "ramos-wet-bar-built-ins-phoenix-east-valley-az-108",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-phoenix-east-valley-az-108.webp",
    "title": "Custom Wet Bar Built In",
    "alt": "Custom wet bar built in cabinetry by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 115
  },
  {
    "slug": "ramos-wet-bar-built-ins-tempe-east-valley-az-109",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-tempe-east-valley-az-109.webp",
    "title": "Custom Wet Bar Built In",
    "alt": "Custom wet bar built in cabinetry by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 77
  },
  {
    "slug": "ramos-wet-bar-built-ins-gilbert-east-valley-az-110",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-gilbert-east-valley-az-110.webp",
    "title": "Custom Wet Bar Built In",
    "alt": "Custom wet bar built in cabinetry by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 80
  },
  {
    "slug": "ramos-wet-bar-built-ins-mesa-east-valley-az-111",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-mesa-east-valley-az-111.webp",
    "title": "Custom Wet Bar Built In",
    "alt": "Custom wet bar built in cabinetry by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 153
  },
  {
    "slug": "ramos-wet-bar-built-ins-chandler-east-valley-az-112",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-chandler-east-valley-az-112.webp",
    "title": "Custom Wet Bar Built In",
    "alt": "Custom wet bar built in cabinetry by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 99
  },
  {
    "slug": "ramos-wet-bar-built-ins-scottsdale-east-valley-az-113",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-scottsdale-east-valley-az-113.webp",
    "title": "Custom Wet Bar Built In",
    "alt": "Custom wet bar built in cabinetry by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 158
  },
  {
    "slug": "ramos-wet-bar-built-ins-phoenix-east-valley-az-114",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-phoenix-east-valley-az-114.webp",
    "title": "Custom Wet Bar Built In",
    "alt": "Custom wet bar built in cabinetry by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1600,
    "height": 1200,
    "sizeKb": 79
  },
  {
    "slug": "ramos-laundry-room-cabinets-tempe-east-valley-az-115",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-tempe-east-valley-az-115.webp",
    "title": "Laundry Room Cabinet Storage",
    "alt": "Laundry room cabinet storage and utility room cabinetry by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 55
  },
  {
    "slug": "ramos-laundry-room-cabinets-gilbert-east-valley-az-116",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-gilbert-east-valley-az-116.webp",
    "title": "Laundry Room Cabinet Storage",
    "alt": "Laundry room cabinet storage and utility room cabinetry by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 62
  },
  {
    "slug": "ramos-laundry-room-cabinets-mesa-east-valley-az-117",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-mesa-east-valley-az-117.webp",
    "title": "Laundry Room Cabinet Storage",
    "alt": "Laundry room cabinet storage and utility room cabinetry by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 66
  },
  {
    "slug": "ramos-laundry-room-cabinets-chandler-east-valley-az-118",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-chandler-east-valley-az-118.webp",
    "title": "Laundry Room Cabinet Storage",
    "alt": "Laundry room cabinet storage and utility room cabinetry by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1600,
    "height": 1600,
    "sizeKb": 136
  },
  {
    "slug": "ramos-laundry-room-cabinets-scottsdale-east-valley-az-119",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-scottsdale-east-valley-az-119.webp",
    "title": "Laundry Room Cabinet Storage",
    "alt": "Laundry room cabinet storage and utility room cabinetry by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1600,
    "height": 1600,
    "sizeKb": 63
  },
  {
    "slug": "ramos-laundry-room-cabinets-phoenix-east-valley-az-120",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-phoenix-east-valley-az-120.webp",
    "title": "Laundry Room Cabinet Storage",
    "alt": "Laundry room cabinet storage and utility room cabinetry by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1600,
    "height": 1600,
    "sizeKb": 70
  },
  {
    "slug": "ramos-laundry-room-cabinets-tempe-east-valley-az-121",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-tempe-east-valley-az-121.webp",
    "title": "Laundry Room Cabinet Storage",
    "alt": "Laundry room cabinet storage and utility room cabinetry by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1600,
    "height": 1600,
    "sizeKb": 138
  },
  {
    "slug": "ramos-laundry-room-cabinets-gilbert-east-valley-az-122",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-gilbert-east-valley-az-122.webp",
    "title": "Laundry Room Cabinet Storage",
    "alt": "Laundry room cabinet storage and utility room cabinetry by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1600,
    "height": 1200,
    "sizeKb": 148
  },
  {
    "slug": "ramos-laundry-room-cabinets-mesa-east-valley-az-123",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-mesa-east-valley-az-123.webp",
    "title": "Laundry Room Cabinet Storage",
    "alt": "Laundry room cabinet storage and utility room cabinetry by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 85
  },
  {
    "slug": "ramos-kitchen-remodeling-chandler-east-valley-az-124",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-chandler-east-valley-az-124.webp",
    "title": "Kitchen Island Cabinet Detail",
    "alt": "Kitchen island cabinet detail by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 97
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-125",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-125.webp",
    "title": "Kitchen Island Cabinet Detail",
    "alt": "Kitchen island cabinet detail by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 112
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-126",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-126.webp",
    "title": "Kitchen Island Cabinet Detail",
    "alt": "Kitchen island cabinet detail by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 109
  },
  {
    "slug": "ramos-wet-bar-built-ins-tempe-east-valley-az-127",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-tempe-east-valley-az-127.webp",
    "title": "Custom Bar Cabinet Detail",
    "alt": "Custom bar cabinet detail and wood finish by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 131
  },
  {
    "slug": "ramos-wet-bar-built-ins-gilbert-east-valley-az-128",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-gilbert-east-valley-az-128.webp",
    "title": "Custom Bar Cabinet Detail",
    "alt": "Custom bar cabinet detail and wood finish by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 104
  },
  {
    "slug": "ramos-wet-bar-built-ins-mesa-east-valley-az-129",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-mesa-east-valley-az-129.webp",
    "title": "Custom Bar Cabinet Detail",
    "alt": "Custom bar cabinet detail and wood finish by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 98
  },
  {
    "slug": "ramos-laundry-room-cabinets-chandler-east-valley-az-130",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-chandler-east-valley-az-130.webp",
    "title": "Laundry Room Cabinet Remodel",
    "alt": "Laundry room cabinet remodel by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 967,
    "height": 1600,
    "sizeKb": 79
  },
  {
    "slug": "ramos-laundry-room-cabinets-scottsdale-east-valley-az-131",
    "image": "/images/projects/seo/ramos-laundry-room-cabinets-scottsdale-east-valley-az-131.webp",
    "title": "Laundry Room Cabinet Remodel",
    "alt": "Laundry room cabinet remodel by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "laundry-room-cabinets",
    "categoryLabel": "Laundry Room Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 85
  },
  {
    "slug": "ramos-custom-cabinets-phoenix-east-valley-az-132",
    "image": "/images/projects/seo/ramos-custom-cabinets-phoenix-east-valley-az-132.webp",
    "title": "Custom Cabinet Door Storage",
    "alt": "Custom cabinet door storage and tall cabinet by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1079,
    "height": 1600,
    "sizeKb": 39
  },
  {
    "slug": "ramos-custom-cabinets-tempe-east-valley-az-133",
    "image": "/images/projects/seo/ramos-custom-cabinets-tempe-east-valley-az-133.webp",
    "title": "Custom Cabinet Door Storage",
    "alt": "Custom cabinet door storage and tall cabinet by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 61
  },
  {
    "slug": "ramos-wet-bar-built-ins-gilbert-east-valley-az-134",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-gilbert-east-valley-az-134.webp",
    "title": "Home Bar Cabinetry",
    "alt": "Home bar cabinetry with beverage storage by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 98
  },
  {
    "slug": "ramos-wet-bar-built-ins-mesa-east-valley-az-135",
    "image": "/images/projects/seo/ramos-wet-bar-built-ins-mesa-east-valley-az-135.webp",
    "title": "Home Bar Cabinetry",
    "alt": "Home bar cabinetry with beverage storage by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "wet-bar-built-ins",
    "categoryLabel": "Wet Bar Built Ins",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 97
  },
  {
    "slug": "ramos-custom-cabinets-chandler-east-valley-az-136",
    "image": "/images/projects/seo/ramos-custom-cabinets-chandler-east-valley-az-136.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1206,
    "height": 1409,
    "sizeKb": 116
  },
  {
    "slug": "ramos-custom-cabinets-scottsdale-east-valley-az-137",
    "image": "/images/projects/seo/ramos-custom-cabinets-scottsdale-east-valley-az-137.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 74
  },
  {
    "slug": "ramos-custom-cabinets-phoenix-east-valley-az-138",
    "image": "/images/projects/seo/ramos-custom-cabinets-phoenix-east-valley-az-138.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 93
  },
  {
    "slug": "ramos-custom-cabinets-tempe-east-valley-az-139",
    "image": "/images/projects/seo/ramos-custom-cabinets-tempe-east-valley-az-139.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 55
  },
  {
    "slug": "ramos-custom-cabinets-gilbert-east-valley-az-140",
    "image": "/images/projects/seo/ramos-custom-cabinets-gilbert-east-valley-az-140.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 66
  },
  {
    "slug": "ramos-custom-cabinets-mesa-east-valley-az-141",
    "image": "/images/projects/seo/ramos-custom-cabinets-mesa-east-valley-az-141.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 151
  },
  {
    "slug": "ramos-custom-cabinets-chandler-east-valley-az-142",
    "image": "/images/projects/seo/ramos-custom-cabinets-chandler-east-valley-az-142.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 107
  },
  {
    "slug": "ramos-custom-cabinets-scottsdale-east-valley-az-143",
    "image": "/images/projects/seo/ramos-custom-cabinets-scottsdale-east-valley-az-143.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 57
  },
  {
    "slug": "ramos-custom-cabinets-phoenix-east-valley-az-144",
    "image": "/images/projects/seo/ramos-custom-cabinets-phoenix-east-valley-az-144.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 42
  },
  {
    "slug": "ramos-custom-cabinets-tempe-east-valley-az-145",
    "image": "/images/projects/seo/ramos-custom-cabinets-tempe-east-valley-az-145.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 65
  },
  {
    "slug": "ramos-custom-cabinets-gilbert-east-valley-az-146",
    "image": "/images/projects/seo/ramos-custom-cabinets-gilbert-east-valley-az-146.webp",
    "title": "Custom Storage Cabinetry",
    "alt": "Custom storage cabinetry and built in cabinets by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "custom-cabinets",
    "categoryLabel": "Custom Cabinets",
    "serviceSlug": "custom-cabinets",
    "serviceHref": "/services/custom-cabinets",
    "width": 1200,
    "height": 1600,
    "sizeKb": 67
  },
  {
    "slug": "ramos-closet-built-ins-mesa-east-valley-az-147",
    "image": "/images/projects/seo/ramos-closet-built-ins-mesa-east-valley-az-147.webp",
    "title": "Closet Built In Storage",
    "alt": "Closet built in storage and cabinet drawers by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "closet-built-ins",
    "categoryLabel": "Closet Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 59
  },
  {
    "slug": "ramos-closet-built-ins-chandler-east-valley-az-148",
    "image": "/images/projects/seo/ramos-closet-built-ins-chandler-east-valley-az-148.webp",
    "title": "Closet Built In Storage",
    "alt": "Closet built in storage and cabinet drawers by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "closet-built-ins",
    "categoryLabel": "Closet Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 97
  },
  {
    "slug": "ramos-closet-built-ins-scottsdale-east-valley-az-149",
    "image": "/images/projects/seo/ramos-closet-built-ins-scottsdale-east-valley-az-149.webp",
    "title": "Closet Built In Storage",
    "alt": "Closet built in storage and cabinet drawers by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "closet-built-ins",
    "categoryLabel": "Closet Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 720,
    "height": 960,
    "sizeKb": 27
  },
  {
    "slug": "ramos-closet-built-ins-phoenix-east-valley-az-150",
    "image": "/images/projects/seo/ramos-closet-built-ins-phoenix-east-valley-az-150.webp",
    "title": "Closet Built In Storage",
    "alt": "Closet built in storage and cabinet drawers by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "closet-built-ins",
    "categoryLabel": "Closet Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1600,
    "height": 1200,
    "sizeKb": 57
  },
  {
    "slug": "ramos-closet-built-ins-tempe-east-valley-az-151",
    "image": "/images/projects/seo/ramos-closet-built-ins-tempe-east-valley-az-151.webp",
    "title": "Closet Built In Storage",
    "alt": "Closet built in storage and cabinet drawers by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "closet-built-ins",
    "categoryLabel": "Closet Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 63
  },
  {
    "slug": "ramos-closet-built-ins-gilbert-east-valley-az-152",
    "image": "/images/projects/seo/ramos-closet-built-ins-gilbert-east-valley-az-152.webp",
    "title": "Closet Built In Storage",
    "alt": "Closet built in storage and cabinet drawers by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "closet-built-ins",
    "categoryLabel": "Closet Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 70
  },
  {
    "slug": "ramos-closet-built-ins-mesa-east-valley-az-153",
    "image": "/images/projects/seo/ramos-closet-built-ins-mesa-east-valley-az-153.webp",
    "title": "Closet Built In Storage",
    "alt": "Closet built in storage and cabinet drawers by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "closet-built-ins",
    "categoryLabel": "Closet Built Ins",
    "serviceSlug": "finish-carpentry",
    "serviceHref": "/services/finish-carpentry",
    "width": 1200,
    "height": 1600,
    "sizeKb": 75
  },
  {
    "slug": "ramos-cabinet-installation-chandler-east-valley-az-154",
    "image": "/images/projects/seo/ramos-cabinet-installation-chandler-east-valley-az-154.webp",
    "title": "Cabinet Installation and Remodel Prep",
    "alt": "Cabinet installation and remodel prep by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 60
  },
  {
    "slug": "ramos-cabinet-installation-scottsdale-east-valley-az-155",
    "image": "/images/projects/seo/ramos-cabinet-installation-scottsdale-east-valley-az-155.webp",
    "title": "Cabinet Installation and Remodel Prep",
    "alt": "Cabinet installation and remodel prep by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 768,
    "height": 1152,
    "sizeKb": 65
  },
  {
    "slug": "ramos-cabinet-installation-phoenix-east-valley-az-156",
    "image": "/images/projects/seo/ramos-cabinet-installation-phoenix-east-valley-az-156.webp",
    "title": "Cabinet Installation and Remodel Prep",
    "alt": "Cabinet installation and remodel prep by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 88
  },
  {
    "slug": "ramos-cabinet-installation-tempe-east-valley-az-157",
    "image": "/images/projects/seo/ramos-cabinet-installation-tempe-east-valley-az-157.webp",
    "title": "Cabinet Installation and Remodel Prep",
    "alt": "Cabinet installation and remodel prep by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 69
  },
  {
    "slug": "ramos-cabinet-installation-gilbert-east-valley-az-158",
    "image": "/images/projects/seo/ramos-cabinet-installation-gilbert-east-valley-az-158.webp",
    "title": "Cabinet Installation and Remodel Prep",
    "alt": "Cabinet installation and remodel prep by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 62
  },
  {
    "slug": "ramos-cabinet-installation-mesa-east-valley-az-159",
    "image": "/images/projects/seo/ramos-cabinet-installation-mesa-east-valley-az-159.webp",
    "title": "Cabinet Installation and Remodel Prep",
    "alt": "Cabinet installation and remodel prep by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 153
  },
  {
    "slug": "ramos-cabinet-installation-chandler-east-valley-az-160",
    "image": "/images/projects/seo/ramos-cabinet-installation-chandler-east-valley-az-160.webp",
    "title": "Cabinet Installation and Remodel Prep",
    "alt": "Cabinet installation and remodel prep by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "cabinet-installation",
    "categoryLabel": "Cabinet Installation",
    "serviceSlug": "cabinet-installation",
    "serviceHref": "/services/cabinet-installation",
    "width": 1200,
    "height": 1600,
    "sizeKb": 83
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-161",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-161.webp",
    "title": "Kitchen Remodel Design and Build",
    "alt": "Kitchen remodel design and cabinet build by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1600,
    "height": 1200,
    "sizeKb": 72
  },
  {
    "slug": "ramos-kitchen-remodeling-phoenix-east-valley-az-162",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-phoenix-east-valley-az-162.webp",
    "title": "Kitchen Remodel Design and Build",
    "alt": "Kitchen remodel design and cabinet build by Ramos Cabinetry and Construction in Phoenix, AZ",
    "city": "Phoenix, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 118
  },
  {
    "slug": "ramos-kitchen-remodeling-tempe-east-valley-az-163",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-tempe-east-valley-az-163.webp",
    "title": "Kitchen Remodel Design and Build",
    "alt": "Kitchen remodel design and cabinet build by Ramos Cabinetry and Construction in Tempe, AZ",
    "city": "Tempe, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1280,
    "height": 960,
    "sizeKb": 56
  },
  {
    "slug": "ramos-kitchen-remodeling-gilbert-east-valley-az-164",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-gilbert-east-valley-az-164.webp",
    "title": "Kitchen Remodel Design and Build",
    "alt": "Kitchen remodel design and cabinet build by Ramos Cabinetry and Construction in Gilbert, AZ",
    "city": "Gilbert, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 98
  },
  {
    "slug": "ramos-kitchen-remodeling-mesa-east-valley-az-165",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-mesa-east-valley-az-165.webp",
    "title": "Kitchen Remodel Design and Build",
    "alt": "Kitchen remodel design and cabinet build by Ramos Cabinetry and Construction in Mesa, AZ",
    "city": "Mesa, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 144
  },
  {
    "slug": "ramos-kitchen-remodeling-chandler-east-valley-az-166",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-chandler-east-valley-az-166.webp",
    "title": "Kitchen Remodel Design and Build",
    "alt": "Kitchen remodel design and cabinet build by Ramos Cabinetry and Construction in Chandler, AZ",
    "city": "Chandler, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1200,
    "height": 1600,
    "sizeKb": 98
  },
  {
    "slug": "ramos-kitchen-remodeling-scottsdale-east-valley-az-167",
    "image": "/images/projects/seo/ramos-kitchen-remodeling-scottsdale-east-valley-az-167.webp",
    "title": "Kitchen Remodel Design and Build",
    "alt": "Kitchen remodel design and cabinet build by Ramos Cabinetry and Construction in Scottsdale, AZ",
    "city": "Scottsdale, AZ",
    "category": "kitchen-remodeling",
    "categoryLabel": "Kitchen Remodeling",
    "serviceSlug": "kitchen-remodeling",
    "serviceHref": "/services/kitchen-remodeling",
    "width": 1600,
    "height": 1200,
    "sizeKb": 106
  }
];

export const galleryCategories = Array.from(
  new Map(projectGallery.map((item) => [item.category, item.categoryLabel])).entries(),
).map(([slug, label]) => ({ slug, label }));

export function getGalleryForService(serviceSlug: string, limit = 6) {
  return projectGallery.filter((item) => item.serviceSlug === serviceSlug).slice(0, limit);
}
